[[nomin]]
= Nomin
:icons:
:toc: macro
:toc-title:
:toclevels: 1

image:https://circleci.com/gh/nomin-project/nomin.svg?style=svg["CircleCI", link="https://circleci.com/gh/nomin-project/nomin"]

toc::[]

[[welcome]]
== Welcome to Nomin!

Nomin is a graphical application which allows you to send an email from addresses of famous curators to the email boxes of various fine art bienals, prizes and other cultural institutions.
With Nomin being recommended as an artist by world top curators is matter of few clicks, not years long process of boring networking.
Nomin is here to help you with pushing your aristic career beyond all the thinkable horizons!

We fully understand that the usage of Nomin can be questioned for its ethical aspects.
Some could call it dishonest or scum, but we call it "art".
Not only an app, Nomin is also an artistic project criticising the art world - a collective performance of all of us.
Project in which you can freely and fairly participate.
Just recommend yourself and get your exhibitions, or say "it was just an art".

If you want to know more about this defensive attitude, please read our https://github.com/nomin-project/nomin/blob/master/docs/artistic-statement.adoc[artistic statement].

[[getting-started]]
== Getting started

=== Installation

To download the latest version of Nomin for Linux, macOS or Windows, see the https://github.com/nomin-project/nomin/releases[Nomin releases] page.
Once the Nomin binary is downloaded you can run it:

- on Windows just double-click the downloaded `nomin.exe` file
- on Linux double-click the binary or start it from terminal by executing `./nomin-linux` command
- on Mac you need first to extract the downloaded archive and then start the binary inside of it

If you have any troubles with above instructions or need more detailed explanation of it, please visit our https://github.com/nomin-project/nomin/blob/master/docs/installation.adoc[Installation guide].  

=== Configuring SMTP

To be able to successfully send the email Nomin needs the information about which open SMTP server it should use.
Please navigate to the "Define a mail server" part of the Window and insert the address and port of the SMTP server you want to use.

This is the most unfriendly part of the Nomin usage.
If you do not know which address to insert, please visit our https://github.com/nomin-project/nomin/blob/master/docs/smtp.adoc[SMTP Guide] which will help you. 

=== Sending the email

==== Using templates

Nomin gives the option to use predefined templates.
These are templates for the sender of the email, its recipient and the text of the actual email.
These can be accessed in "Select sender and recipient" part of the Nomin window.
However you are not obligged to use them at all.

==== Editing the email text

If you have used the templates or not, navigate your sight to "Write the email" part of the Nomin window, where you can edit or write the complete email by yourself.
We recommend to try to send the email to your own mailbox at first to see if everything works well.

==== Sending

Once you are done and happy with whole email, hit the send button and wait for confirming pop-up message in the Nomin window.
If you see the "Message has been successfully sent" you are done.
Congratulations, your first fake email has been sent.

We wish you best of luck with your exhibition!

[[additional-information]]
== Additional information
=== Privacy statement

Nomin does not collect any subject or text of the emails sent with it.
To improve its usage Nomin however collects the data about the sender's and recipient's email addresses and the SMTP server used.
Its reason is to add more usable SMTP servers to the Nomin and have data about which galleries and curators are popular.
Privacy of the users is however untouched because the texts and strategies they use to fool galleries is kept absolutely private.
Texts and subjects of emails are private.
This is secured also by keeping the source code of the Nomin open and publicly available.

[[help]]
== Getting help, resolving problems

If you are facing any trouble while using Nomin, please visit our https://github.com/nomin-project/nomin/issuess[Bug Tracker] here on Github.
We are thankful for any feedback and willing to answer any Nomin related question there.
Also if you have any suggestion for future functionality or improvement of Nomin, let us know.

[[community]]
== Community

Nomin is an open source collaborative project dedicated to help the beginning artists with their success.
We appreciate any bug report, suggestion for improvement, sharing of the project or other kind of help.
Feel free to get in touch with us.

=== Contact

To contact the developer of this project, please write an email to `andreas.gajdosik@gmail.com`.

=== Thanks to:

- https://github.com/asticode[Quentin Renard] - author of https://github.com/asticode/go-astilectron-demo[go-astilectron-demo],
- Marketa Wagnerova - photography for the Nomin website,
- Anna Tesarova - model and suggestions,
- Tomas Panacik Moravansky - important bug reports. 
